version: "3.8"
services:
  recommendation-redis:
    container_name: pick-cake-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: kailcali09/pick-cake-reserve-redis
    ports:
      - "6379:6379"


  recommendation-db:
    container_name: pick-cake-db
    build:
      dockerfile: Dockerfile
      context: ./db
    image: kailcali09/pick-cake-reserve-db
    environment:
      - MARIADB_DATABASE=pickcake
      - MARIADB_ROOT_PASSWORD=${MARIA_SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./db/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"

