
### sign-in with no valid password
### sign-in
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "hail09@gmail.com",
  "password": "1234notvalid"
}


### 401
GET http://localhost:8080/api/cake
