package co.pickcake.aop.util;

public enum ErrorCode {
    DUPLICATED_USER_ALREADY_EXISTS,
    COULD_NOT_CANCEL_FOR_CAMPED_ITEM,

    ITEM_NAME_NOT_FOUND,
    BRAND_NAME_NOT_FOUND,
    SHOP_NAME_NOT_FOUND,

    /* Exception Handling error code */
    NO_DATA_EXISTS,
    BAD_REQUEST,
    BAD_GATEWAY,
    METHOD_ARGUMENT_NOT_VALID,

    NO_AUTHENTICATION_EXISTS,

    NO_SUCH_USER_FOUND,

}
