
### sign-up
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "userId": "hail09@gmail.com",
  "password": "1234",
  "userName": "hail-test",
  "address": {
    "city": "seoul",
    "street": "yonsei",
    "zipcode": "33111"
  }
}

### sign-in
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "hail09@gmail.com",
  "password": "1234"
}

### chekc 200
GET http://localhost:8080/api/cake

### check 401
GET http://localhost:8080/admin

